### ISSUE TITLE
Channel won't collapse automatically

### ISSUE THREAD

**Issue by psh4377** [programmer2514/BetterDiscord-CollapsibleUI#149]
![{B65FF928-3152-49AC-9FF3-2EDAB3CBED0D}](https://github.com/user-attachments/assets/1f4ebfda-9226-413e-a7d3-becbb4b9d405)

Server button works
but channe button doesn't do any work.
It works when I disable UI Transitions.
When the window size change, all the button turns off.

**Comment by davipbl** [comment]
same here. Had to disable ui transitions

**Comment by Kilvoctu** [comment]
Confirming issue. All buttons work except Channel

**Comment by ashergz** [comment]
Adding another confirmation. I know it's holiday season but please acknowledge soon

**Comment by programmer2514** [comment]
I am aware of this issue, but will not be able to fix it for around a week due to the holidays. Thanks for your patience and for the reports!

**Comment by programmer2514** [comment]
This should be fixed in v9 :)

**Comment by AlexBilozir** [comment]
> This should be fixed in v9 :)
After updating betterdiscord and the whole client crashes :/

**Comment by programmer2514** [comment]
> After updating betterdiscord and the whole client crashes :/

That is really odd...are you able to reproduce this behavior or was it a one-time occurrence?

One thing you can try if you believe the issue was caused by CollapsibleUI is deleting the file `CollapsibleUI.config.json` in your plugins folder, then restarting Discord. This update pushes major configuration changes and I have seen some cases of corrupt config files in the past during a migration.

**Comment by Kilvoctu** [comment]
It's working for me. There were some minor issues that were resolved after restarting Discord.
Thank you for the update!

**Comment by AlexBilozir** [comment]
> > After updating betterdiscord and the whole client crashes :/
> 
> That is really odd...are you able to reproduce this behavior or was it a one-time occurrence?
> 
> One thing you can try if you believe the issue was caused by CollapsibleUI is deleting the file `CollapsibleUI.config.json` in your plugins folder, then restarting Discord. This update pushes major configuration changes and I have seen some cases of corrupt config files in the past during a migration.

Im sure problem in CollapsibleUI. Tried deleting the file `CollapsibleUI.config.json` didn't help. uninstalled betterdiscord and all plugins and reinstalled and added only collapseUI. still crashes.

Recorded screencast how crash looks. 

I use MacOS Sequoia 15.1.1. and I use 2 discord clients at the same time. Everything worked perfectly. Then the animation stopped working. Following the advice here, I disabled UI Transitions, it helped. But after update to v9 client crashes now.

I recorded the work of one client with a full window on the screencast to show that it's the plugin, not the fact that I use 2 clients.

**Comment by programmer2514** [comment]
That's concerning...I don't have any Apple devices, and since this issue appears to be Mac-specific, it may be difficult for me to debug. Can you confirm that this stops happening with CollapsibleUI disabled or deleted? If not, try reinstalling BetterDiscord, but if so, shoot me a message on Discord @tenorthehusky so I can help resolve the issue.

**Comment by AlexBilozir** [comment]
> Can you confirm that this stops happening with CollapsibleUI disabled or deleted?

yes
