### ISSUE TITLE
Resizing channel panel can go beyond window width

### ISSUE THREAD

**Issue by dnk-codes** [programmer2514/BetterDiscord-CollapsibleUI#44]
![Peek 2022-09-06 09-20](https://user-images.githubusercontent.com/43136638/188571916-ae04ece1-8f18-4440-8232-11b1943ed2c8.gif)

**Comment by programmer2514** [comment]
I can't fix this seamlessly due to the way the CSS resize property is handled, but I have a solution that will work well enough. Should be fixed in the next release

**Comment by dnk-codes** [comment]
I don't know, seems it is still broken, I'll take a look at it and maybe write a better bug report with more detail

**Comment by programmer2514** [comment]
Wow...sorry about that, I was really tired yesterday (had just gotten back from an 8 hour drive to New York). Not really sure what I was thinking with the fix I implemented but you are correct, it was pretty broken. I found an actual solution and it should be fixed now
